### ISSUE TITLE
Mark compatibility with Symphony 2.6

### ISSUE THREAD

**Issue by michael-e** [symphonycms/markdown#12]
I am rather sure that this extension will be compatible with Symphony 2.6.

Correct? If yes, I can send a pull request with new release information in the README.

**Comment by nitriques** [comment]
Yes! please do! Formatters have not been touched if I remember correctly.

**Comment by michael-e** [comment]
Reading [this comment](https://github.com/symphonycms/profiledevkit/issues/5#issue-47585708), should we even use `2.x.x` as max value? What do you think?

**Comment by nitriques** [comment]
Yes!! I've been rooting for this for a long time now :)

**Comment by michael-e** [comment]
This has been done, so I am gonna close this.

**Comment by nitriques** [comment]
Thanks @michael-e
